package com.realitsolutions.demo;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import com.realitsolutions.demo.model.Response;
import com.realitsolutions.demo.model.PromptRequest;

public class Test001Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    private PromptRequest promptRequest;
    private Response response;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void test001() {
        WebDriver driver = new ChromeDriver();

        promptRequest.setPrompt("Write a Java code to print even numbers till 10");

        driver.get("https://chat.openai.com/auth/login?iss=https%3A%2F%2Fauth0.openai.com%2F");
        driver.manage().window().setSize(new Dimension(699, 728));
        driver.findElement(By.cssSelector(".relative:nth-child(1) > .relative")).click();
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("fokidav917@trazeco.com");
        driver.findElement(By.cssSelector(".\\_widget")).click();
        driver.findElement(By.name("action")).click();
        driver.findElement(By.id("password")).sendKeys("Password@123");
        driver.findElement(By.cssSelector(".cd6a2dc65")).click();
        driver.findElement(By.id("prompt-textarea")).click();
        driver.findElement(By.id("prompt-textarea")).sendKeys(promptRequest.getPrompt());
        driver.findElement(By.cssSelector(".p-1 > span")).click();
        js.executeScript("window.scrollTo(0,0)");
    }
}
